INSERT INTO tb_product (name, description, image, price) VALUES ('Product 50', 'Description for Product 50', 'https://cdn.example.com/products/50.jpg', 500.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 49', 'Description for Product 49', 'https://cdn.example.com/products/49.jpg', 490.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 48', 'Description for Product 48', 'https://cdn.example.com/products/48.jpg', 480.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 47', 'Description for Product 47', 'https://cdn.example.com/products/47.jpg', 470.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 46', 'Description for Product 46', 'https://cdn.example.com/products/46.jpg', 460.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 45', 'Description for Product 45', 'https://cdn.example.com/products/45.jpg', 450.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 44', 'Description for Product 44', 'https://cdn.example.com/products/44.jpg', 440.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 43', 'Description for Product 43', 'https://cdn.example.com/products/43.jpg', 430.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 42', 'Description for Product 42', 'https://cdn.example.com/products/42.jpg', 420.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 41', 'Description for Product 41', 'https://cdn.example.com/products/41.jpg', 410.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 40', 'Description for Product 40', 'https://cdn.example.com/products/40.jpg', 400.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 39', 'Description for Product 39', 'https://cdn.example.com/products/39.jpg', 390.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 38', 'Description for Product 38', 'https://cdn.example.com/products/38.jpg', 380.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 37', 'Description for Product 37', 'https://cdn.example.com/products/37.jpg', 370.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 36', 'Description for Product 36', 'https://cdn.example.com/products/36.jpg', 360.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 35', 'Description for Product 35', 'https://cdn.example.com/products/35.jpg', 350.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 34', 'Description for Product 34', 'https://cdn.example.com/products/34.jpg', 340.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 33', 'Description for Product 33', 'https://cdn.example.com/products/33.jpg', 330.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 32', 'Description for Product 32', 'https://cdn.example.com/products/32.jpg', 320.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 31', 'Description for Product 31', 'https://cdn.example.com/products/31.jpg', 310.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 30', 'Description for Product 30', 'https://cdn.example.com/products/30.jpg', 300.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 29', 'Description for Product 29', 'https://cdn.example.com/products/29.jpg', 290.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 28', 'Description for Product 28', 'https://cdn.example.com/products/28.jpg', 280.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 27', 'Description for Product 27', 'https://cdn.example.com/products/27.jpg', 270.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 26', 'Description for Product 26', 'https://cdn.example.com/products/26.jpg', 260.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 25', 'Description for Product 25', 'https://cdn.example.com/products/25.jpg', 250.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 24', 'Description for Product 24', 'https://cdn.example.com/products/24.jpg', 240.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 23', 'Description for Product 23', 'https://cdn.example.com/products/23.jpg', 230.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 22', 'Description for Product 22', 'https://cdn.example.com/products/22.jpg', 220.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 21', 'Description for Product 21', 'https://cdn.example.com/products/21.jpg', 210.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 20', 'Description for Product 20', 'https://cdn.example.com/products/20.jpg', 200.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 19', 'Description for Product 19', 'https://cdn.example.com/products/19.jpg', 190.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 18', 'Description for Product 18', 'https://cdn.example.com/products/18.jpg', 180.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 17', 'Description for Product 17', 'https://cdn.example.com/products/17.jpg', 170.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 16', 'Description for Product 16', 'https://cdn.example.com/products/16.jpg', 160.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 15', 'Description for Product 15', 'https://cdn.example.com/products/15.jpg', 150.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 14', 'Description for Product 14', 'https://cdn.example.com/products/14.jpg', 140.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 13', 'Description for Product 13', 'https://cdn.example.com/products/13.jpg', 130.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 12', 'Description for Product 12', 'https://cdn.example.com/products/12.jpg', 120.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 11', 'Description for Product 11', 'https://cdn.example.com/products/11.jpg', 110.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 10', 'Description for Product 10', 'https://cdn.example.com/products/10.jpg', 100.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 09', 'Description for Product 09', 'https://cdn.example.com/products/09.jpg', 90.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 08', 'Description for Product 08', 'https://cdn.example.com/products/08.jpg', 80.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 07', 'Description for Product 07', 'https://cdn.example.com/products/07.jpg', 70.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 06', 'Description for Product 06', 'https://cdn.example.com/products/06.jpg', 60.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 05', 'Description for Product 05', 'https://cdn.example.com/products/05.jpg', 50.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 04', 'Description for Product 04', 'https://cdn.example.com/products/04.jpg', 40.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 03', 'Description for Product 03', 'https://cdn.example.com/products/03.jpg', 30.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 02', 'Description for Product 02', 'https://cdn.example.com/products/02.jpg', 20.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Product 01', 'Description for Product 01', 'https://cdn.example.com/products/01.jpg', 10.00);
INSERT INTO tb_product (name, description, image, price) VALUES ('Duplicate', 'Description for Duplicate', 'https://cdn.example.com/products/duplicate-a.jpg', 99.90);
INSERT INTO tb_product (name, description, image, price) VALUES ('Duplicate', 'Description for Duplicate', 'https://cdn.example.com/products/duplicate-b.jpg', 109.90);

INSERT INTO tb_category (id, name) VALUES (1, 'Computers');
INSERT INTO tb_category (id, name) VALUES (2, 'Electronics');
INSERT INTO tb_category (id, name) VALUES (3, 'Accessories');

INSERT INTO tb_product_category (product_id, category_id) VALUES (1, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (1, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 3);
